version: "3.3"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx4g
      - cluster.routing.allocation.disk.threshold_enabled=false
    ports:
      - "9200:9200"
    networks:
      - elastic
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    user: 1000:1000

networks:
  elastic: